<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>2.0.2</Version>
        <TargetFramework>net10.0-android</TargetFramework>
        <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsBindingProject>true</IsBindingProject>
        <RepositoryUrl>https://github.com/Truvideo/truvideo-sdk-video-android-net</RepositoryUrl>
        <MauiVersion>10.0.10</MauiVersion>
    </PropertyGroup>

    <ItemGroup>
        <NLIGradleProjectReference Include="../TruVideoVideoAndroid">
            <ModuleName>TruvideoVideo</ModuleName>
        </NLIGradleProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
        <PackageReference Include="CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks" Version="0.0.1-pre1" />

        <!-- ✅ Media3 latest NuGets -->
        <PackageReference Include="Xamarin.AndroidX.Media3.Transformer" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.ExoPlayer" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.UI" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.Common" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.Extractor" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.DataSource" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.Container" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.Decoder" Version="1.9.0" />
        <PackageReference Include="Xamarin.AndroidX.Media3.Database" Version="1.9.0" />
    </ItemGroup>
    <!-- Android AAR/JAR references -->
    <ItemGroup Condition="$(TargetFramework.Contains('android'))">

        <!-- TruVideo Video SDK -->
        <AndroidLibrary Include="../TruVideoVideoAndroid/TruvideoVideo/libs/sdk-video-1.0.5.aar" Bind="false" Visible="false" />
        <AndroidLibrary Include="../TruVideoVideoAndroid/TruvideoVideo/libs/truvideo-sdk-android-video-utils-1.0.5.aar" Bind="false" Visible="false" />
        <AndroidLibrary Include="../TruVideoVideoAndroid/TruvideoVideo/libs/truvideo-sdk-android-video-utils-exceptions-1.0.2.jar" Bind="false" Visible="false" />
    </ItemGroup>
</Project>



